.TH "PKGWATCH" "1" "July 2009" "" ""
.SH "NAME"
pkgwatch \- an arch out\-of\-date package notifier

.SH "SYNOPSIS"
pkgwatch [option]
.SH "DESCRIPTION"
pkgwatch is a (very) simple out\-of\-date notifier for Arch packages. At the moment, it's nowhere near where I envision it. My long term goal is to enable users to check for upstream updates instead of simply reading whether or not packages are marked out\-of\-date.
.SH "OPTIONS"
.TP 
\fB\-h\fR, \fB\-\-help\fR
Display help and exit
.TP 
\fB\-v\fR, \fB\-\-version\fR
Display version and exit
.TP 
\fB\-n\fR, \fB\-\-notify\fR
Output to notification daemon
.SH "AUTHORS"
Ghost1227
