#!/bin/bash
#
# pkgwatch v0.4 - Arch out of date package notifier.
# Copyright (C) 2009 Daniel J Griffiths <ghost1227@archlinux.us>
# Thanks to:
#            Wonder & Louipc for the initial idea
#            Rson for helping track down the bugs in 0.2
#                 and submitting a good bit of code cleanup
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.

VER=0.4
NOTIFY=0
INFO="\e[1;33m==>\e[1;37m"
ERROR="\e[1;31m==>\e[1;37m"
SUCCESS="\e[1;32m==>\e[1;37m"
RESET="\e[0m"

unset USER

if [ -f /tmp/pkgwatch ]; then
	rm -f /tmp/pkgwatch
fi

##############################
### VERSION FUNCTION       ###
##############################
version() {
	echo "pkgwatch v$VER"
}

##############################
### USAGE FUNCTION         ###
##############################
usage() {
	version
	echo
	echo "pkgwatch [option]"
	echo "	-h, --help	Display help and exit"
	echo "	-v, --version	Display version and exit"
	echo "	-n, --notify	Output to notification daemon"
}

##############################
### GET FUNCTION           ###
##############################
get() {
	if [ -z $USER ]; then
		if [ -f $HOME/.config/pkgwatch/config ]; then
			source $HOME/.config/pkgwatch/config
		fi
	fi

	if [ -z $USER ]; then
		echo -e "$ERROR Missing configuration information!"
		echo -e "$ERROR Please pass a username or set \"USER=username\" in $HOME/.config/pkgwatch/config$RESET"
		exit 1
	fi

	TOTAL=`wget -q -O - "http://aur.archlinux.org/packages.php?O=0&K=$USER&do_Search=Go&detail=1&L=2&C=0&SeB=m&SB=n&SO=a&PP=100&outdated=on" | grep "Showing results" | awk '{ print $7}'`

	if [ -z $TOTAL ]; then
		SINGLE=`wget -q -O - "http://aur.archlinux.org/packages.php?O=0&K=$USER&do_Search=Go&detail=1&L=2&C=0&SeB=m&SB=n&SO=a&PP=100&outdated=on" | grep "class='f2'" | awk -F">" '{ print $2 }' | awk '{ print $1 }'`

		if [ -z $SINGLE ]; then
			EXIST=`wget -q -O - "http://aur.archlinux.org/packages.php?O=0&K=$USER&do_Search=Go&detail=1&L=2&C=0&SeB=m&SB=n&SO=a&PP=100" | grep "No packages" | awk '{ print $2 }' | awk -F">" '{ print $2 }'`
			if [ -z $EXIST ]; then
				echo -e "$SUCCESS No packages out of date!$RESET"
				exit 0
			else
				echo -e "$ERROR User '$USER' does not exist!$RESET"
				exit 1
			fi
		else
			echo $SINGLE >> /tmp/pkgwatch
		fi
	else
		OFFSET=0
		while [ $OFFSET -lt $TOTAL ]; do
			wget -q -O - "http://aur.archlinux.org/packages.php?O=$OFFSET&K=$USER&do_Search=Go&detail=1&L=2&C=0&SeB=m&SB=n&SO=a&PP=100&outdated=on" | grep "class='f4'" | awk -F">" '{ print $5 }' | awk '{ print $1 }' | sed -e '/^$/d' >> /tmp/pkgwatch
			let OFFSET=OFFSET+100
		done
	fi

	if [ $NOTIFY -eq 1 ]; then
		OOD=$(< /tmp/pkgwatch)
		notify-send "Out of date packages:" "$OOD"
	else
		echo -e "$INFO The following packages are marked out of date:"
		echo -e "`cat /tmp/pkgwatch`$RESET"
	fi

	exit 0
}

##############################
### GET RUNTIME ARGS       ###
##############################

while [ "$#" -ne "0" ]; do
	case $1 in
		'-n'|'--notify')
		let NOTIFY=1
		;;
		'-h'|'--help')
		usage
		exit 0
		;;
		'-v'|'--version')
		version
		exit 0
		;;
		*)
		USER=$1
		;;
	esac
	shift
done

get

exit 0


